name: Build and test Qbs for Baremetal on Windows

on: [push]

jobs:
  build-qbs-with-qbs-using-mingw:
    name: Build Qbs with Qbs using MinGW
    runs-on: [self-hosted, windows, x64]
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v1
    - name: Setup origin Qbs toolchain
      run: |
        ${QBS_ORIG_PATH}/qbs config --unset profiles
        ${QBS_ORIG_PATH}/qbs setup-toolchains --type mingw g++.exe mingw-orig
        ${QBS_ORIG_PATH}/qbs setup-qt ${QMAKE_PATH} qt-orig
        ${QBS_ORIG_PATH}/qbs config profiles.qt-orig.baseProfile mingw-orig
        ${QBS_ORIG_PATH}/qbs config --list
      shell: bash
    - name: Build target Qbs
      run: |
        ${QBS_ORIG_PATH}/qbs resolve profile:qt-orig config:release project.withDocumentation:false
        ${QBS_ORIG_PATH}/qbs build profile:qt-orig config:release project.withDocumentation:false
      shell: bash

  test-baremetal-windows:
    name: Run Baremetal tests on Windows
    runs-on: [self-hosted, windows, x64]
    timeout-minutes: 10
    needs: build-qbs-with-qbs-using-mingw
    steps:
    - name: Update PATH
      run: echo "${PWD}/release/install-root/bin" >> $GITHUB_PATH
      shell: bash
    - name: Detect toolchains
      run: |
        qbs config --unset profiles
        qbs setup-toolchains --detect
      shell: bash
