name: Build and test Qbs for Baremetal on Windows

on: [push]

jobs:
#  build-qbs-with-qbs-using-mingw:
#    name: Build Qbs with Qbs using MinGW
#    runs-on: [self-hosted, windows, x64]
#    timeout-minutes: 30
#    steps:
#    - uses: actions/checkout@v1
#    - name: Setup origin Qbs toolchain
#      run: |
#        ${QBS_ORIG_PATH}/qbs config --unset profiles
#        ${QBS_ORIG_PATH}/qbs setup-toolchains --type mingw ${MINGW_ORIG_PATH}/g++.exe mingw-orig
#        ${QBS_ORIG_PATH}/qbs setup-qt ${QT_ORIG_PATH}/qmake.exe qt-orig
#        ${QBS_ORIG_PATH}/qbs config profiles.qt-orig.baseProfile mingw-orig
#        ${QBS_ORIG_PATH}/qbs config --list
#      shell: bash
#    - name: Build target Qbs
#      run: |
#        ${QBS_ORIG_PATH}/qbs resolve profile:qt-orig config:release project.withDocumentation:false
#        ${QBS_ORIG_PATH}/qbs build profile:qt-orig config:release project.withDocumentation:false
#      shell: bash

  test-baremetal-windows:
    name: Run Baremetal tests on Windows
    runs-on: [self-hosted, windows, x64]
    timeout-minutes: 10
#    needs: build-qbs-with-qbs-using-mingw
    steps:
    - name: Setup target Qbs run environment
      run: |
        export PATH=${QT_ORIG_PATH}:${MINGW_ORIG_PATH}
        echo "Qbs run environment is: ${PATH}"
        cd ${PWD}/release/install-root/bin
        echo "Working directory is: ${PWD}"
      shell: bash
    - name: Setup target Qbs toolchains
      run: |
        qbs.exe --version
      shell: bash
