name: Build and test Qbs for Baremetal on Windows

on: [push]

jobs:
  test-windows-baremetal:
    name: test baremetal
    runs-on: [self-hosted, windows, x64]
  steps:
  - uses: actions/checkout@v1
  - name: print
    run: echo "hello"
    shell: bash
